---
version: "2"
services:
  puck:
    image: denstark/puck:latest
    container_name: puck
    environment:
      - TZ=America/New_York
    volumes:
      - ./config.rb:/app/config.rb
      - ./quotesdb.sqlite3:/quotes.sqlite3
      - .:/app
    restart: unless-stopped
